// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("banco")]
public partial class Banco
{
    [Key]
    [Column("idBanco", TypeName = "int(11)")]
    public int IdBanco { get; set; }

    [Column(TypeName = "int(11)")]
    public int Descripcion { get; set; }

    public virtual ICollection<CobroCheque> CobroCheques { get; set; } = new List<CobroCheque>();
    public virtual ICollection<PagoCheque> PagoCheques { get; set; } = new List<PagoCheque>();
}