// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("banco")]
public class Banco
{
    [Key]
    [Column("idBanco", TypeName = "int(11)")]
    public int IdBanco { get; set; }

    [Column(TypeName = "char")]
    [StringLength(50, ErrorMessage = "El nombre del Banco no puede superar los 50 caracteres")]
    public string Descripcion { get; set; }

    public virtual ICollection<CobroCheque> CobroCheques { get; set; } = new List<CobroCheque>();
    public virtual ICollection<PagoCheque> PagoCheques { get; set; } = new List<PagoCheque>();
}