// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("camion")]
[Index("IdTipoCamion", Name = "FK_CAMION_TIPOCAMION")]
[Index("NroChasis", Name = "id_numero_chasis", IsUnique = true)]
[Index("NroMotor", Name = "id_numero_motor", IsUnique = true)]
public class Camion
{
    [Key]
    [Column("idCamion", TypeName = "int(11)")]
    public int IdCamion { get; set; }

    [Required]
    [StringLength(10)]
    public string Patente { get; set; }

    [StringLength(20)]
    public string Marca { get; set; }

    [StringLength(20)]
    public string Modelo { get; set; }

    [Required]
    [StringLength(50)]
    public string NroChasis { get; set; }

    [Required]
    [StringLength(50)]
    public string NroMotor { get; set; }

    [Column("idTipoCamion", TypeName = "int(11)")]
    public int? IdTipoCamion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaAlta { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaBaja { get; set; }

    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime? UserDateTime { get; set; }

    public virtual TipoCamion TipoCamion { get; set; }
    public virtual ICollection<Mantenimiento> Mantenimientos { get; set; } = new List<Mantenimiento>();
    public virtual ICollection<Viaje> Viajes { get; set; } = new List<Viaje>();
}