// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("chofer")]
[Index("Dni", Name = "id_dni", IsUnique = true)]
[Index("NroRegistro", Name = "id_nro_registro", IsUnique = true)]
public class Chofer
{
    [Key]
    [Column("idChofer", TypeName = "int(11)")]
    public int IdChofer { get; set; }

    [Required]
    [Column("nombre")]
    [StringLength(20)]
    public string Nombre { get; set; }

    [Required]
    [Column("apellido")]
    [StringLength(20)]
    public string Apellido { get; set; }

    [Column("telefono", TypeName = "int(11)")]
    public int? Telefono { get; set; }

    [Column("direccion")]
    [StringLength(50)]
    public string Direccion { get; set; }

    [Column("dni", TypeName = "int(11)")]
    public int Dni { get; set; }

    /// <summary>
    /// Nro Registro Profecional
    /// </summary>
    [Column("nroRegistro", TypeName = "bigint(20)")]
    public long? NroRegistro { get; set; }

    [Column("fechaAlta", TypeName = "datetime")]
    public DateTime FechaAlta { get; set; }

    [Column("fechaBaja", TypeName = "datetime")]
    public DateTime FechaBaja { get; set; }

    [Required]
    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime UserDateTime { get; set; }

    public virtual ICollection<Viaje> Viajes { get; set; } = new List<Viaje>();
}