// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Seminario.Datos.Entidades.Interfaces;

namespace Seminario.Datos.Entidades;

[Table("chofer")]
[Index("Dni", Name = "id_dni", IsUnique = true)]
[Index("NroRegistro", Name = "id_nro_registro", IsUnique = true)]
public class Chofer : IAuditable
{
    [Key]
    [Column("idChofer", TypeName = "int(11)")]
    public int IdChofer { get; set; }

    [Required]
    [Column("nombre")]
    [StringLength(20)]
    public string Nombre { get; set; }

    [Required]
    [Column("apellido")]
    [StringLength(20)]
    public string Apellido { get; set; }

    [Column("telefono", TypeName = "int(11)")]
    public int? Telefono { get; set; }

    [Column("direccion")]
    [StringLength(50)]
    public string Direccion { get; set; }

    [Column("dni", TypeName = "int(11)")]
    public int Dni { get; set; }

    /// <summary>
    /// Nro Registro Profesional
    /// </summary>
    [Column("nroRegistro", TypeName = "varchar(50)")]
    public string NroRegistro { get; set; }

    [Column("fechaAlta", TypeName = "datetime")]
    public DateTime FechaAlta { get; set; }

    [Column("fechaBaja", TypeName = "datetime")]
    public DateTime? FechaBaja { get; set; }

    [Required]
    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime UserDateTime { get; set; }

    public virtual ICollection<Viaje> Viajes { get; set; } = new List<Viaje>();

    public static Chofer Create()
    {
        return new Chofer
        {
            IdChofer = 0,
            Nombre = null,
            Apellido = null,
            Telefono = null,
            Direccion = null,
            Dni = 0,
            NroRegistro = null,
            FechaAlta = default,
            FechaBaja = null,
            UserName = null,
            UserDateTime = default,
            Viajes = null
        };
    }

    public void CreatedAt(DateTime time, string userName)
    {
        this.UserDateTime = time;
        this.UserName = userName;
    }

    public void ModifiedAt(DateTime time, string userName)
    {
        this.UserDateTime = time;
        this.UserName = userName;
    }
}