// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Seminario.Datos.Entidades.Interfaces;

namespace Seminario.Datos.Entidades;

[Table("cliente")]
public  class Cliente : IAuditable
{
    [Key]
    [Column("idCliente", TypeName = "int(11)")]
    public int IdCliente { get; set; }

    [Column("cuit")]
    [MaxLength(11)]
    public string Cuit { get; set; }

    [Column("razonSocial")]
    [StringLength(50)]
    public string RazonSocial { get; set; }

    [Column("direccion")]
    [StringLength(30)]
    public string Direccion { get; set; }

    [Column("telefono", TypeName = "int(11)")]
    public int? Telefono { get; set; }

    [Column("mail")]
    [StringLength(50)]
    public string Mail { get; set; }

    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime? UserDateTime { get; set; }
    
    [Column("FechaBaja", TypeName = "datetime")]
    public DateTime? FechaBaja { get; set; }
    
    public virtual ICollection<Viaje> Viajes { get; set; } = new List<Viaje>();
    public void CreatedAt(DateTime date, string user)
    {
        UserName = user;
        UserDateTime = date;
        
    }

    public void ModifiedAt(DateTime date, string user)
    {
        UserName = user;
        UserDateTime = date;
    }
}