// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("cliente")]
public partial class Cliente
{
    [Key]
    [Column("idCliente", TypeName = "int(11)")]
    public int IdCliente { get; set; }

    [Column("cuit")]
    [StringLength(30)]
    public string Cuit { get; set; }

    [Column("razonSocial")]
    [StringLength(50)]
    public string RazonSocial { get; set; }

    [Column("direccion")]
    [StringLength(30)]
    public string Direccion { get; set; }

    [Column("telefono", TypeName = "int(11)")]
    public int? Telefono { get; set; }

    [Column("mail")]
    [StringLength(50)]
    public string Mail { get; set; }

    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime? UserDateTime { get; set; }
    public virtual ICollection<Viaje> Viajes { get; set; } = new List<Viaje>();
}