// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Seminario.Datos.Entidades.Interfaces;

namespace Seminario.Datos.Entidades;

[Table("cobro")]
[Index("IdFormaPago", Name = "FK_COBRO_FORMAPAGO")]
[Index("IdMoneda", Name = "FK_COBRO_MONEDA")]
[Index("IdViaje", Name = "FK_COBRO_VIAJE")]
public  class Cobro : IAuditable
{
    [Key]
    [Column("idCobro", TypeName = "int(11)")]
    public int IdCobro { get; set; }

    [Column(TypeName = "int(11)")]
    public int IdViaje { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaRecibo { get; set; }

    [Precision(10, 0)]
    public decimal Monto { get; set; }

    [Column("idMoneda", TypeName = "int(11)")]
    public int IdMoneda { get; set; }

    public double TipoCambio { get; set; }

    [Column("idFormaPago", TypeName = "int(11)")]
    public int IdFormaPago { get; set; }
    
    [Column("idPagoCheque", TypeName = "int(11)")]
    public int? IdPagoCheque { get; set; }
    
    [Column("cobroAnulado",TypeName = "int(11)")]
    public int? CobroAnulado { get; set; }

    [Column("userName", TypeName = "varchar(15)")]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime? UserDateTime { get; set; }

    public virtual FormaPago FormaPago { get; set; }
    public virtual Moneda Moneda { get; set; }
    public virtual Viaje Viaje{ get; set; }
    public virtual PagoCheque Cheque { get; set; }

    public void CreatedAt(DateTime date, string user)
    {
        UserName = user;
        UserDateTime = date;
    }

    public void ModifiedAt(DateTime date, string user)
    {
        UserName = user;
        UserDateTime = date;
    }
}