// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("cobro")]
[Index("IdFormaPago", Name = "FK_COBRO_FORMAPAGO")]
[Index("IdMoneda", Name = "FK_COBRO_MONEDA")]
[Index("IdViaje", Name = "FK_COBRO_VIAJE")]
public  class Cobro
{
    [Key]
    [Column("idCobro", TypeName = "int(11)")]
    public int IdCobro { get; set; }

    [Column(TypeName = "int(11)")]
    public int IdViaje { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaRecibo { get; set; }

    [Precision(10, 0)]
    public decimal Monto { get; set; }

    [Column("idMoneda", TypeName = "int(11)")]
    public int IdMoneda { get; set; }

    public double TipoCambio { get; set; }

    [Column("idFormaPago", TypeName = "int(11)")]
    public int IdFormaPago { get; set; }
    
    [Column("idPagoCheque", TypeName = "int(11)")]
    public int? IdPagoCheque { get; set; }
    
    [Column("cobroAnulado",TypeName = "int(11)")]
    public int? CobroAnulado { get; set; }

    public virtual FormaPago FormaPago { get; set; }
    public virtual Moneda Moneda { get; set; }
    public virtual Viaje Viaje{ get; set; }
    public virtual PagoCheque Cheque { get; set; }
}