// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("cobrocheque")]
[Index("IdCobro", Name = "FK_COBROCHEQUE_COBRO")]
[Index("IdBanco", "NroCheque", "CuitEmisor", Name = "id_unique_cobro_cheque", IsUnique = true)]
public partial class CobroCheque
{
    [Key]
    [Column("idCobroCheque", TypeName = "int(11)")]
    public int IdCobroCheque { get; set; }

    [Column("idCobro", TypeName = "int(11)")]
    public int IdCobro { get; set; }

    [Column("nroCheque", TypeName = "int(11)")]
    public int NroCheque { get; set; }

    [Column("cuitEmisor", TypeName = "int(11)")]
    public int CuitEmisor { get; set; }

    [Column("idBanco", TypeName = "int(11)")]
    public int IdBanco { get; set; }

    [Column("fechaCobro", TypeName = "datetime")]
    public DateTime FechaCobro { get; set; }

    [Column("fechaDepositado", TypeName = "datetime")]
    public DateTime? FechaDepositado { get; set; }

    [Column("fechaVencimiento", TypeName = "datetime")]
    public DateTime FechaVencimiento { get; set; }

    [Column("rechazado")]
    public bool Rechazado { get; set; }
    public virtual Banco Banco { get; set; }
    public virtual Cobro Cobro { get; set; }
}