// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("compra/repuesto")]
[Index("IdMantenimiento", Name = "FK_COMPRAREPUESTO_MANTENIMIENTO")]
[Index("IdProveedor", Name = "FK_COMPRAREPUESTO_PROVEEDOR")]
public  class CompraRepuesto
{
    [Key]
    [Column("idCompraRepuesto", TypeName = "int(11)")]
    public int IdCompraRepuesto { get; set; }

    [Column("idMantenimiento", TypeName = "int(11)")]
    public int? IdMantenimiento { get; set; }

    [Column("fecha", TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    [Column("idProveedor", TypeName = "int(11)")]
    public int IdProveedor { get; set; }

    [Column("iva%")]
    public float Iva { get; set; }
    public virtual ICollection<CompraRepuestoDetalle> Detalles { get; set; } = new List<CompraRepuestoDetalle>();
    public virtual Mantenimiento Mantenimiento { get; set; }
    public virtual Proveedor Proveedor { get; set; }
    public virtual ICollection<PagoCompraRepuesto> PagoCompraRepuestos { get; set; } = new List<PagoCompraRepuesto>();
}