// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("compra/repuesto/detalle")]
[Index("IdCompraRepuesto", Name = "FK_DETALLE_COMPRA/REPUESTO")]
public partial class CompraRepuestoDetalle
{
    [Key]
    [Column("idDetalle", TypeName = "int(11)")]
    public int IdDetalle { get; set; }

    [Column("idCompraRepuesto", TypeName = "int(11)")]
    public int IdCompraRepuesto { get; set; }

    [Required]
    [Column("descripcion")]
    [StringLength(1000)]
    public string Descripcion { get; set; }

    [Column("cantidad")]
    public float Cantidad { get; set; }

    [Column("precioUnitario")]
    public float PrecioUnitario { get; set; }
    public virtual CompraRepuesto CompraRepuesto { get; set; }
}