// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("especialidad")]
public  class Especialidad
{
    [Key]
    [Column("idEspecialidad", TypeName = "int(11)")]
    public int IdEspecialidad { get; set; }

    [Required]
    [StringLength(50)]
    public string Descripcion { get; set; }
    public virtual ICollection<ProveedorEspecialidad> ProveedorEspecialidades { get; set; } = new List<ProveedorEspecialidad>();
    public virtual ICollection<TallerEspecialidad> TallerEspecialidades { get; set; } = new List<TallerEspecialidad>();

    public static Especialidad Create()
    {
        return new Especialidad();
    }
}