// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("localidad")]
[Index("IdProvincia", Name = "FK_LOCALIDAD_PROVINCIA")]
public  class Localidad
{
    [Key]
    [Column("idLocalidad", TypeName = "int(11)")]
    public int IdLocalidad { get; set; }

    [Required]
    [MaxLength(50)]
    public string Descripcion { get; set; }

    [Column("idProvincia", TypeName = "int(11)")]
    public int IdProvincia { get; set; }

    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime? UserDateTime { get; set; }
    public virtual Provincia Provincia { get; set; }
    public virtual ICollection<Proveedor> Proveedores { get; set; } = new List<Proveedor>();
    public virtual ICollection<Taller> Talleres { get; set; } = new List<Taller>();
    public virtual ICollection<Destino> Destinos { get; set; } = new List<Destino>();
    public virtual ICollection<Procedencia> Procedencias { get; set; } = new List<Procedencia>();
}