// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Seminario.Datos.Entidades.Interfaces;

namespace Seminario.Datos.Entidades;

[Table("mantenimiento/tarea")]
[Index("IdMantenimiento", Name = "FK_MANTENIMIENTO/TAREA_MANTENIEMIENTO")]
public  class MantenimientoTarea : IAuditable
{
    [Key]
    [Column("idTarea", TypeName = "int(11)")]
    public int IdTarea { get; set; }

    [Column("idMantenimiento", TypeName = "int(11)")]
    public int IdMantenimiento { get; set; }

    [Required]
    [Column("descripcion")]
    [StringLength(50)]
    public string Descripcion { get; set; }

    [Column("costo")]
    [Precision(10, 0)]
    public decimal? Costo { get; set; }

    [Column("fecha", TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime UserDateTime { get; set; }

    [Required]
    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }
    public virtual Mantenimiento Mantenimiento { get; set; }
    public void CreatedAt(DateTime date, string user)
    {
        UserDateTime = date;
        UserName = user;
    }

    public void ModifiedAt(DateTime date, string user)
    {
        UserDateTime = date;
        UserName = user;
    }
}