// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Seminario.Datos.Entidades.Interfaces;

namespace Seminario.Datos.Entidades;

[Table("mantenimiento/observacion")]
[Index("IdMantenimiento", Name = "FK_MANTENIMIENTO/OBSERVACION_MANTENIEMIENTO")]
public  class MantenimientoObservacion : IAuditable
{
    [Key]
    [Column("idObservacion", TypeName = "int(11)")]
    public int IdObservacion { get; set; }

    [Column("idMantenimiento", TypeName = "int(11)")]
    public int IdMantenimiento { get; set; }

    [Required]
    [Column("observacion")]
    [StringLength(1000)]
    public string Observacion { get; set; }

    [Column("fecha", TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime UserDateTime { get; set; }

    [Required]
    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }
    public virtual Mantenimiento Mantenimiento { get; set; }
    public void CreatedAt(DateTime date, string user)
    {
        UserDateTime = date;
        UserName = user;
    }

    public void ModifiedAt(DateTime date, string user)
    {
        UserDateTime = date;
        UserName = user;
    }
}