// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("mantenimiento")]
[Index("IdVehiculo", Name = "FK_MANTENIMIENTO_CAMION")]
[Index("IdTaller", Name = "FK_MANTENIMIENTO_TALLER")]
public  class Mantenimiento
{
    [Key]
    [Column("idMantenimiento", TypeName = "int(11)")]
    public int IdMantenimiento { get; set; }

    [Required]
    [Column("titulo")]
    [StringLength(50)]
    public string Titulo { get; set; }

    [Column("idVehiculo", TypeName = "int(11)")]
    public int IdVehiculo { get; set; }

    [Column("fechaEntrada", TypeName = "datetime")]
    public DateTime FechaEntrada { get; set; }

    [Column("fechaSalida", TypeName = "datetime")]
    public DateTime? FechaSalida { get; set; }

    [Column(TypeName = "int(11)")]
    public int KilometrajeVehiculo { get; set; }

    [Column("idTaller", TypeName = "int(11)")]
    public int IdTaller { get; set; }
    public virtual ICollection<CompraRepuesto> CompraRepuestos { get; set; } = new List<CompraRepuesto>();
    public virtual Taller Taller { get; set; }
    public virtual Camion Vehiculo { get; set; }
    public virtual ICollection<MantenimientoObservacion> Observaciones { get; set; } = new List<MantenimientoObservacion>();
    public virtual ICollection<MantenimientoTarea> Tareas { get; set; } = new List<MantenimientoTarea>();
    public virtual ICollection<PagoMantenimiento> PagoMantenimientos { get; set; } = new List<PagoMantenimiento>();
}