// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("moneda")]
public partial class Moneda
{
    [Key]
    [Column("idMoneda", TypeName = "int(11)")]
    public int IdMoneda { get; set; }

    [Required]
    [StringLength(20)]
    public string Descripcion { get; set; }
    public virtual ICollection<Cobro> Cobros { get; set; } = new List<Cobro>();
    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();
}