// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("pago/mantenimiento")]
[Index("IdPago", Name = "FK_PAGOMANTENIMIENTO_PAGO")]
[Index("IdMantenimiento", "IdPago", Name = "id_mantenimiento_pago", IsUnique = true)]
public class PagoMantenimiento
{
    [Key]
    [Column("idPagoMantenimiento", TypeName = "int(11)")]
    public int IdPagoMantenimiento { get; set; }

    [Column("idPago", TypeName = "int(11)")]
    public int IdPago { get; set; }

    [Column("idMantenimiento", TypeName = "int(11)")]
    public int IdMantenimiento { get; set; }

    [Column("importeAplicado")]
    [Precision(10, 0)]
    public decimal ImporteAplicado { get; set; }
    public virtual Mantenimiento Mantenimiento { get; set; }
    public virtual Pago Pago { get; set; }
}