// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("pagocheque")]
[Index("IdBanco", Name = "FK_PAGOCHEQUE_BANCO")]
public  class PagoCheque
{
    [Key]
    [Column("idPagoCheque", TypeName = "int(11)")]
    public int IdPagoCheque { get; set; }

    [Column("nroCheque", TypeName = "int(11)")]
    public int NroCheque { get; set; }

    [Column("esPropio")]
    public bool EsPropio { get; set; }

    [Column("cuitEmisor", TypeName = "bigint")]
    public long CuitEmisor { get; set; }

    [Column("idBanco", TypeName = "int(11)")]
    public int IdBanco { get; set; }

    //Esta fecha hace referencia a la primera fecha que tiene un cheque, es normalmente la fecha de emision
    [Column("fechaCobro", TypeName = "datetime")]
    public DateTime? FechaCobro { get; set; }

    [Column("fechaDeposito", TypeName = "datetime")]
    public DateTime FechaDeposito { get; set; }

    [Column("fechaVencimiento", TypeName = "datetime")]
    public DateTime FechaVencimiento { get; set; }

    [Column("rechazado")]
    public bool Rechazado { get; set; }
    public virtual Banco Banco { get; set; }
    public virtual Pago Pago { get; set; }
    public virtual Cobro Cobro { get; set; }
}