// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("pago")]
[Index("IdFormaPago", Name = "FK_PAGO_FORMAPAGO")]
[Index("IdMoneda", Name = "FK_PAGO_MONEDA")]
public  class Pago
{
    [Key]
    [Column("idPago", TypeName = "int(11)")]
    public int IdPago { get; set; }

    [Column("fechaPago", TypeName = "datetime")]
    public DateTime FechaPago { get; set; }

    [Required]
    [Column("concepto")]
    [StringLength(50)]
    public string Concepto { get; set; }

    [Column("monto")]
    [Precision(10, 0)]
    public decimal Monto { get; set; }

    [Column("idMoneda", TypeName = "int(11)")]
    public int IdMoneda { get; set; }

    public double TipoCambio { get; set; }

    [Column("idFormaPago", TypeName = "int(11)")]
    public int IdFormaPago { get; set; }
    public virtual FormaPago FormaPago { get; set; }
    public virtual Moneda Moneda { get; set; }
    public virtual ICollection<PagoCompraRepuesto> PagoCompraRepuestos { get; set; } = new List<PagoCompraRepuesto>();
    public virtual ICollection<PagoMantenimiento> PagoMantenimientos { get; set; } = new List<PagoMantenimiento>();
    public virtual ICollection<PagoCheque> PagoCheques { get; set; } = new List<PagoCheque>();
}