// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("pago/comprarepuesto")]
[Index("IdPago", Name = "FK_PAGOCOMPRA_PAGO")]
[Index("IdCompraRepuesto", "IdPago", Name = "id_compra_pago", IsUnique = true)]
public partial class PagoCompraRepuesto
{
    [Key]
    [Column("idPagoCompraRepuesto", TypeName = "int(11)")]
    public int IdPagoCompraRepuesto { get; set; }

    [Column("idPago", TypeName = "int(11)")]
    public int IdPago { get; set; }

    [Column("idCompraRepuesto", TypeName = "int(11)")]
    public int IdCompraRepuesto { get; set; }

    [Column("importeAplicado")]
    [Precision(10, 0)]
    public decimal ImporteAplicado { get; set; }
    public virtual CompraRepuesto CompraRepuesto { get; set; }
    public virtual Pago Pago { get; set; }
}