// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("proveedor/especialidad")]
[Index("IdEspecialidad", Name = "FK_PROVEEDOR/ESPECIALIDAD_ESPECIALIDAD")]
[Index("IdProveedor", "IdEspecialidad", Name = "id_proveedor_especialidad", IsUnique = true)]
public partial class ProveedorEspecialidad
{
    [Key]
    [Column("idProveedorEspecialidad", TypeName = "int(11)")]
    public int IdProveedorEspecialidad { get; set; }

    [Column("idProveedor", TypeName = "int(11)")]
    public int IdProveedor { get; set; }

    [Column("idEspecialidad", TypeName = "int(11)")]
    public int IdEspecialidad { get; set; }
    public virtual Especialidad Especialidad { get; set; }
    public virtual Proveedor Proveedor { get; set; }
}