// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("proveedor")]
[Index("IdLocalidad", Name = "FK_PROVEEDOR_LOCALIDAD")]
public class Proveedor
{
    [Key]
    [Column("idProveedor", TypeName = "int(11)")]
    public int IdProveedor { get; set; }

    [Required]
    [Column("razonSocial")]
    [StringLength(50)]
    public string RazonSocial { get; set; }

    [Column("cuit", TypeName = "int(11)")]
    public int Cuit { get; set; }

    [Required]
    [Column("mail")]
    [StringLength(50)]
    public string Mail { get; set; }

    [Required]
    [Column("responsable")]
    [StringLength(50)]
    public string Responsable { get; set; }

    [Required]
    [Column("direccion")]
    [StringLength(30)]
    public string Direccion { get; set; }

    [Column("idLocalidad", TypeName = "int(11)")]
    public int IdLocalidad { get; set; }

    [Column("codigoPostal", TypeName = "mediumint(9)")]
    public int CodigoPostal { get; set; }
    public virtual ICollection<CompraRepuesto> CompraRepuestos { get; set; } = new List<CompraRepuesto>();
    public virtual Localidad Localidad { get; set; }
    public virtual ICollection<ProveedorEspecialidad> ProveedorEspecialidades { get; set; } = new List<ProveedorEspecialidad>();
}