// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("provincia")]
[Index("IdPais", Name = "FK_PROVINCIA_PAIS")]
public partial class Provincia
{
    [Key]
    [Column("idProvincia", TypeName = "int(11)")]
    public int IdProvincia { get; set; }

    [Required]
    [StringLength(50)]
    public string Descripcion { get; set; }

    [Column("idPais", TypeName = "int(11)")]
    public int IdPais { get; set; }

    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime? UserDateTime { get; set; }
    public virtual Pais Pais { get; set; }
    public virtual ICollection<Localidad> Localidades { get; set; } = new List<Localidad>();
}