// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("taller/especialidad")]
[Index("IdEspecialidad", Name = "FK_TALLER/ESPECIALIDAD_ESPECIALIDAD")]
[Index("IdTaller", "IdEspecialidad", Name = "id_taller_especialidad", IsUnique = true)]
public class TallerEspecialidad
{
    [Key]
    [Column("idTallerEspecialidad", TypeName = "int(11)")]
    public int IdTallerEspecialidad { get; set; }

    [Column("idTaller", TypeName = "int(11)")]
    public int IdTaller { get; set; }

    [Column("idEspecialidad", TypeName = "int(11)")]
    public int IdEspecialidad { get; set; }
    public virtual Especialidad Especialidad { get; set; }
    public virtual Taller Taller { get; set; }
}