// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Seminario.Datos.Entidades.Interfaces;

namespace Seminario.Datos.Entidades;

[Table("taller")]
[Index("IdLocalidad", Name = "FK_TALLER_LOCALIDAD")]
public class Taller : IAuditable
{
    [Key]
    [Column("idTaller", TypeName = "int(11)")]
    public int IdTaller { get; set; }

    [Required]
    [Column("nombre")]
    [StringLength(50)]
    public string Nombre { get; set; }

    [Column("cuit", TypeName = "bigint")]
    public long Cuit { get; set; }

    [Column("telefono", TypeName = "int(11)")]
    public int Telefono { get; set; }

    [Column("responsable")]
    [MaxLength(50)]
    public string Responsable { get; set; }

    [Column("mail")]
    [MaxLength(50)]
    public string Mail { get; set; }

    [Column("idLocalidad", TypeName = "int(11)")]
    public int IdLocalidad { get; set; }

    [Column("codigoPostal")]
    [MaxLength(15)]
    public string CodigoPostal { get; set; }
    
    [Column("direccion")]
    [MaxLength(50)]
    public string Direccion { get; set; }
    
    [Column("userName")]
    [MaxLength(15)]
    public string UserName { get; set; }
    
    [Column("userDateTime", TypeName =  "datetime")]
    public DateTime UserDateTime { get; set; }
    public virtual Localidad Localidad { get; set; }
    public virtual ICollection<Mantenimiento> Mantenimientos { get; set; } = new List<Mantenimiento>();
    public virtual ICollection<TallerEspecialidad> TallerEspecialidades { get; set; } = new List<TallerEspecialidad>();
    public void CreatedAt(DateTime date, string user)
    {
        UserDateTime = date;
        user = user;
    }

    public void ModifiedAt(DateTime date, string user)
    {
        UserDateTime = date;
        user = user;
    }
}