// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("taller")]
[Index("IdLocalidad", Name = "FK_TALLER_LOCALIDAD")]
public class Taller
{
    [Key]
    [Column("idTaller", TypeName = "int(11)")]
    public int IdTaller { get; set; }

    [Required]
    [Column("nombre")]
    [StringLength(50)]
    public string Nombre { get; set; }

    [Column("cuit", TypeName = "int(11)")]
    public int Cuit { get; set; }

    [Column("telefono", TypeName = "int(11)")]
    public int Telefono { get; set; }

    [Required]
    [Column("responsable")]
    [StringLength(50)]
    public string Responsable { get; set; }

    [Required]
    [Column("mail")]
    [StringLength(50)]
    public string Mail { get; set; }

    [Column("idLocalidad", TypeName = "int(11)")]
    public int IdLocalidad { get; set; }

    [Column("codigoPostal", TypeName = "int(11)")]
    public int CodigoPostal { get; set; }
    public virtual Localidad Localidad { get; set; }
    public virtual ICollection<Mantenimiento> Mantenimientos { get; set; } = new List<Mantenimiento>();
    public virtual ICollection<TallerEspecialidad> TallerEspecialidades { get; set; } = new List<TallerEspecialidad>();
}