// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("tipoubicacion")]
public partial class TipoUbicacion
{
    [Key]
    [Column("idTipoUbicacion", TypeName = "int(11)")]
    public int IdTipoUbicacion { get; set; }

    [Required]
    [StringLength(50)]
    public string Descripcion { get; set; }

    [Required]
    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime UserDateTime { get; set; }
    public virtual ICollection<Ubicacion> Ubicaciones { get; set; } = new List<Ubicacion>();
}