// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("tipocamion")]
public class TipoCamion
{
    [Key]
    [Column("idTipoCamion", TypeName = "int(11)")]
    public int IdTipoCamion { get; set; }

    [Required]
    [StringLength(50)]
    public string Descripcion { get; set; }

    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime? UserDateTime { get; set; }
    public virtual ICollection<Camion> Camiones { get; set; } = new List<Camion>();
}