// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("ubicacion")]
[Index("IdLocalidad", Name = "FK_UBICACION_LOCALIDAD")]
[Index("IdTipoUbicacion", Name = "FK_UBICACION_TIPOUBICACION")]
public partial class Ubicacion
{
    [Key]
    [Column("idUbicacion", TypeName = "int(11)")]
    public int IdUbicacion { get; set; }

    [Required]
    [Column("direccion")]
    [StringLength(50)]
    public string Direccion { get; set; }

    [Required]
    [Column("descripcion")]
    [StringLength(50)]
    public string Descripcion { get; set; }

    [Column("idLocalidad", TypeName = "int(11)")]
    public int? IdLocalidad { get; set; }

    [Column("idTipoUbicacion", TypeName = "int(11)")]
    public int? IdTipoUbicacion { get; set; }

    [Column("userName")]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column("userDateTime", TypeName = "datetime")]
    public DateTime? UserDateTime { get; set; }
    public virtual Localidad Localidad { get; set; }
    public virtual TipoUbicacion TipoUbicacion { get; set; }
    public virtual ICollection<Viaje> ViajesDestino { get; set; } = new List<Viaje>();
    public virtual ICollection<Viaje> ViajesProcedencia { get; set; } = new List<Viaje>();
}