// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Seminario.Datos.Entidades.Interfaces;

namespace Seminario.Datos.Entidades;

[Table("viaje")]
[Index("IdCamion", Name = "FK_VIAJE_CAMION")]
[Index("IdChofer", Name = "FK_VIAJE_CHOFER")]
[Index("IdCliente", Name = "FK_VIAJE_CLIENTE")]
public class Viaje : IAuditable, ICreatedTrigger, IModifiedTrigger
{
    [Key]
    [Column("idViaje", TypeName = "int(11)")]
    public int IdViaje { get; set; }

    [Column("idCliente", TypeName = "int(11)")]
    public int IdCliente { get; set; }

    [Column("kilometros", TypeName = "decimal(10,2)")]
    [Precision(10, 2)]
    public decimal? Kilometros { get; set; }

    [Column("MontoTotal", TypeName = "decimal(10,2)")]
    [Precision(10, 2)]
    public decimal MontoTotal { get; set; }

    [Column("precioKm", TypeName = "float")]
    public float? PrecioKm { get; set; }

    [Column("Estado" ,TypeName = "int(11)")]
    public int? Estado { get; set; }

    [Column("FechaPartida",TypeName = "datetime")]
    public DateTime FechaPartida { get; set; }

    [Column("FechaDescarga",TypeName = "datetime")]
    public DateTime? FechaDescarga { get; set; }

    [Column("idChofer", TypeName = "int(11)")]
    public int IdChofer { get; set; }

    [Column("idCamion", TypeName = "int(11)")]
    public int IdCamion { get; set; }

    [Column("Carga", TypeName = "char(20)")]
    [StringLength(20)]
    public string Carga { get; set; }

    [Column("Kilos", TypeName = "float")]
    public float? Kilos { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaAlta { get; set; }

    [Required]
    [StringLength(20)]
    public string UserAlta { get; set; }

    [Required]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UserDateTime { get; set; }
    
    [Column("idMoneda", TypeName =  "int(11)")]
    public int? IdMoneda { get; set; }
    
    public virtual ICollection<Cobro> Cobros { get; set; } = new List<Cobro>();
    public virtual Camion Camion { get; set; } = new Camion();
    public virtual Chofer Chofer { get; set; } = new  Chofer();
    public virtual Cliente Cliente { get; set; } = new  Cliente();
    public virtual ICollection<Destino> Destinos { get; set; } = new List<Destino>();
    public virtual ICollection<Procedencia> Procendecias { get; set; } = new List<Procedencia>();


    public static Viaje Create()
    {
        return new Viaje
        {
            IdCliente = 0,
            Kilometros = 0,
            MontoTotal = 0,
            PrecioKm = 0,
            Estado = 0,
            FechaPartida = default,
            FechaDescarga = null,
            IdChofer = 0,
            IdCamion = 0,
            Carga = string.Empty,
            Kilos = 0,
            FechaAlta = default,
            UserAlta = string.Empty,
            UserName = string.Empty,
            UserDateTime = default
        };
    }

    public void CreatedAt(DateTime date, string user)
    {
        this.UserDateTime = date;
        this.UserName = user;
        this.UserAlta = user;
    }

    public void ModifiedAt(DateTime date, string user)
    {
        this.UserDateTime = date;
        this.UserName = user;
    }

    void ICreatedTrigger.Trigger()
    {
        this.PrecioKm = (float)(MontoTotal / Kilometros);
    }

    void IModifiedTrigger.Trigger()
    {
        this.PrecioKm = (float)(MontoTotal / Kilometros);
        //
        if(this.FechaDescarga >= DateTime.Today && Estado == EstadosViaje.EnViaje.ToInt())
            this.Estado = EstadosViaje.Finalizado.ToInt();
        //
        var cobrado = Cobros.Sum(c => c.Monto);
        if (cobrado == MontoTotal && Estado < EstadosViaje.Suspendido.ToInt())
            this.Estado = EstadosViaje.Cobrado.ToInt();
    }
}