// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seminario.Datos.Entidades;

[Table("viaje")]
[Index("IdCamion", Name = "FK_VIAJE_CAMION")]
[Index("IdChofer", Name = "FK_VIAJE_CHOFER")]
[Index("IdCliente", Name = "FK_VIAJE_CLIENTE")]
[Index("IdDestino", Name = "FK_VIAJE_DESTINO")]
[Index("IdProcendecia", Name = "FK_VIAJE_PROCEDENCIA")]
public partial class Viaje
{
    [Key]
    [Column("idViaje", TypeName = "int(11)")]
    public int IdViaje { get; set; }

    [Column("idCliente", TypeName = "int(11)")]
    public int IdCliente { get; set; }

    [Precision(10, 0)]
    public decimal Kilometros { get; set; }

    [Precision(10, 0)]
    public decimal MontoTotal { get; set; }

    public float PrecioKm { get; set; }

    [Column(TypeName = "int(11)")]
    public int? Estado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaPartida { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaDescarga { get; set; }

    [Column("idChofer", TypeName = "int(11)")]
    public int IdChofer { get; set; }

    [Column("idCamion", TypeName = "int(11)")]
    public int IdCamion { get; set; }

    [StringLength(20)]
    public string Carga { get; set; }

    public float Kilos { get; set; }

    [Column("idProcendecia", TypeName = "int(11)")]
    public int IdProcendecia { get; set; }

    [Column("idDestino", TypeName = "int(11)")]
    public int IdDestino { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaAlta { get; set; }

    [Required]
    [StringLength(20)]
    public string UserAlta { get; set; }

    [Required]
    [StringLength(20)]
    public string UserName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UserDateTime { get; set; }
    public virtual ICollection<Cobro> Cobros { get; set; } = new List<Cobro>();
    public virtual Camion Camion { get; set; }
    public virtual Chofer Chofer { get; set; }
    public virtual Cliente Cliente { get; set; }
    public virtual Ubicacion Destino { get; set; }
    public virtual Ubicacion Procendecia { get; set; }
}