CREATE TABLE IF NOT EXISTS ArchivosCamiones
(
Id BIGINT NOT NULL AUTO_INCREMENT,
Archivo VARCHAR(100) NULL,
IdCamion INT NULL,
FileId VARCHAR(255) NULL,
Fecha DATETIME NULL,
UserName VARCHAR(20) NULL,

CONSTRAINT PK_ArchivosCamiones PRIMARY KEY (Id)
)